name: Setup NodeJS

on:
  workflow_dispatch:

jobs:
  nodejs-job:
    runs-on: ubuntu-latest
    
    steps:
    - name: Install NodeJS
      uses: actions/setup-node@v5
      with:
        node-version: 22

    - name: Check NodeJS version
      run: node --version
  
